"""검색어 목적 분리 점검표 (2026-09-19).

검색창에 칠 법한 말과 "이렇게 나와야 한다" 를 모아 둔다. 사전(purpose-details.json · purpose_text.py ·
query_parse.SEARCH_PHRASES)을 고칠 때마다 돌려 한 번에 본다.

    .venv/bin/python report_query_cases.py        # 표로 보기 (틀린 것만: --fail)
    .venv/bin/python -m unittest test_query_cases  # 전부 맞는지

한 줄: (검색어, 목적, 세부분류, 성별, 무드 글자)
  목적·세부분류는 순서까지 맞아야 한다. 성별은 None/"female"/"male". 무드는 SigLIP 에 넘길 글자.
"""

P, C, F, W, PET, B, E = "personal", "couple", "friendship", "wedding", "pet", "commercial", "event"

CASES = {
    "목적 이름만": [
        ("개인", [P], [], None, ""),
        ("커플", [C], [], None, ""),
        ("연인", [C], [], None, ""),
        ("우정", [F], [], None, ""),
        ("친구", [F], [], None, ""),
        ("베프", [F], [], None, ""),
        ("웨딩", [W], [], None, ""),
        ("결혼", [W], [], None, ""),
        ("반려동물", [PET], [], None, ""),
        ("펫", [PET], [], None, ""),
        ("상업", [B], [], None, ""),
        ("행사", [E], [], None, ""),
    ],
    "목적 + 형식 말(스냅·촬영·사진)": [
        ("개인 스냅", [P], [], None, ""),
        ("개인스냅", [P], [], None, ""),
        ("개인 촬영", [P], [], None, ""),
        ("커플스냅", [C], [], None, ""),
        ("커플 촬영", [C], [], None, ""),
        ("커플 사진", [C], [], None, ""),
        ("데이트 스냅", [C], [], None, ""),
        ("우정스냅", [F], [], None, ""),
        ("친구 촬영", [F], [], None, ""),
        ("웨딩 스냅", [W], [], None, ""),
        ("웨딩사진", [W], [], None, ""),
        ("반려동물 촬영", [PET], [], None, ""),
        ("펫 스냅", [PET], [], None, ""),
        ("상업 촬영", [B], [], None, ""),
        ("행사 사진", [E], [], None, ""),
        ("스냅", [], [], None, ""),
        ("사진", [], [], None, ""),
        ("촬영", [], [], None, ""),
    ],
    "세부분류": [
        ("프로필", [P], ["personal.profile"], None, ""),
        ("프로필 촬영", [P], ["personal.profile"], None, ""),
        ("바디프로필", [P], ["personal.body_profile"], None, ""),
        ("바프", [P], ["personal.body_profile"], None, ""),
        ("증명사진", [P], ["personal.id_photo"], None, ""),
        ("여권사진", [P], ["personal.id_photo"], None, ""),
        ("취업사진", [P], ["personal.id_photo"], None, ""),
        ("기념일", [C], ["couple.anniversary"], None, ""),
        ("프러포즈", [C], ["couple.anniversary"], None, ""),
        ("신혼여행", [C], [], None, ""),
        ("형제", [F], ["friendship.siblings"], None, ""),
        ("자매 스냅", [F], ["friendship.siblings"], None, ""),
        ("본식", [W], ["wedding.ceremony"], None, ""),
        ("본식 스냅", [W], ["wedding.ceremony"], None, ""),
        ("결혼식", [W], ["wedding.ceremony"], None, ""),
        ("하객", [W], ["wedding.ceremony"], None, ""),
        ("웨딩촬영", [W], ["wedding.shoot"], None, ""),
        ("야외웨딩", [W], ["wedding.shoot"], None, ""),
        ("셀프웨딩", [W], ["wedding.shoot"], None, ""),
        ("리마인드웨딩", [W], ["wedding.remind"], None, ""),
        ("강아지", [PET], ["pet.dog"], None, ""),
        ("댕댕이", [PET], ["pet.dog"], None, ""),
        ("고양이", [PET], ["pet.cat"], None, ""),
        ("반려견 스냅", [PET], ["pet.dog"], None, ""),
        ("브랜드", [B], ["commercial.brand"], None, ""),
        ("쇼핑몰", [B], ["commercial.lookbook"], None, ""),
        ("룩북", [B], ["commercial.lookbook"], None, ""),
        ("제품촬영", [B], ["commercial.product"], None, ""),
        ("비즈니스 프로필", [B], ["commercial.business_profile"], None, ""),
        ("메뉴 사진", [B], ["commercial.food_space"], None, ""),
        ("만삭", [E], ["event.maternity"], None, ""),
        ("만삭 스냅", [E], ["event.maternity"], None, ""),
        ("임신", [E], ["event.maternity"], None, ""),
        ("아기", [E], ["event.baby"], None, ""),
        ("신생아", [E], ["event.baby"], None, ""),
        ("백일", [E], ["event.baby"], None, ""),
        ("베이비 스냅", [E], ["event.baby"], None, ""),
        ("돌", [E], ["event.first_birthday"], None, ""),
        ("돌잔치", [E], ["event.first_birthday"], None, ""),
        ("첫돌", [E], ["event.first_birthday"], None, ""),
        ("가족사진", [E], ["event.family"], None, ""),
        ("졸업", [E], ["event.graduation"], None, ""),
        ("졸업 스냅", [E], ["event.graduation"], None, ""),
        ("졸업식", [E], ["event.graduation"], None, ""),
        ("단체사진", [E], ["event.group"], None, ""),
        ("동호회", [E], ["event.group"], None, ""),
        ("다인원 촬영", [E], ["event.group"], None, ""),
        ("생일", [E], ["event.banquet"], None, ""),
        ("환갑", [E], ["event.banquet"], None, ""),
    ],
    "성별": [
        ("여자", [P], [], "female", ""),
        ("남자", [P], [], "male", ""),
        ("여성", [P], [], "female", ""),
        ("남성", [P], [], "male", ""),
        ("여자 스냅", [P], [], "female", ""),
        ("남자 프로필", [P], ["personal.profile"], "male", ""),
        ("여자 바디프로필", [P], ["personal.body_profile"], "female", ""),
        ("남자 노을", [P], [], "male", "노을"),
        ("여자 커플", [C], [], None, ""),
        ("남자 커플스냅", [C], [], None, ""),
        ("남자 웨딩", [W], [], None, ""),
        ("남자친구", [C], [], None, ""),
        ("여자친구랑 데이트", [C], [], None, ""),
        ("남자 여자", [P], [], None, "남자 여자"),
    ],
    "목적 + 무드": [
        ("가을 커플스냅", [C], [], None, "가을"),
        ("노을 커플", [C], [], None, "노을"),
        ("벚꽃 웨딩", [W], [], None, "벚꽃"),
        ("바다 우정스냅", [F], [], None, "바다"),
        ("따뜻한 만삭 사진", [E], ["event.maternity"], None, "따뜻한"),
        ("흑백 프로필", [P], ["personal.profile"], None, "흑백"),
        ("한강 데이트", [C], [], None, "한강"),
        ("강아지랑 산책", [PET], ["pet.dog"], None, "산책"),
        ("비오는 날 커플", [C], [], None, "비오는 날"),
        ("필름 감성 개인 스냅", [P], [], None, "필름 감성"),
        ("몽환적인 웨딩", [W], [], None, "몽환적인"),
        ("쇼핑몰 화보", [B], ["commercial.lookbook"], None, "화보"),
    ],
    "무드만": [
        ("노을", [], [], None, "노을"),
        ("몽환적인 노을", [], [], None, "몽환적인 노을"),
        ("벚꽃", [], [], None, "벚꽃"),
        ("흑백", [], [], None, "흑백"),
        ("필름 감성", [], [], None, "필름 감성"),
        ("화보", [], [], None, "화보"),
        ("한복", [], [], None, "한복"),
        ("바다", [], [], None, "바다"),
        ("청량한", [], [], None, "청량한"),
        ("인테리어 예쁜 카페", [], [], None, "인테리어 예쁜 카페"),
    ],
    "헷갈리는 말 (목적이 아니다)": [
        ("아기자기한 카페", [], [], None, "아기자기한 카페"),
        ("돌담길", [], [], None, "돌담길"),
        ("돌계단", [], [], None, "돌계단"),
        ("개인적인 분위기", [], [], None, "개인적인 분위기"),
        ("가족 같은 따뜻함", [], [], None, "가족 같은 따뜻함"),
        ("친구 같은 편안함", [], [], None, "친구 같은 편안함"),
        ("강아지풀", [], [], None, "강아지풀"),
        ("연회장 조명", [], [], None, "연회장 조명"),
        ("상업적인 느낌", [], [], None, "상업적인 느낌"),
        ("브랜드 로고", [B], ["commercial.brand"], None, "로고"),
    ],
    "여러 목적": [
        ("웨딩 커플", [W], [], None, ""),
        ("커플 강아지", [C, PET], ["pet.dog"], None, ""),
        ("가족 강아지", [PET, E], ["event.family", "pet.dog"], None, ""),   # 세부분류는 검색어 순서대로
        ("친구 커플", [C, F], [], None, ""),
        ("만삭 우정스냅", [F, E], ["event.maternity"], None, ""),
        ("커플 프로필", [C], [], None, ""),
        ("웨딩 강아지", [W, PET], ["pet.dog"], None, ""),
    ],
    "띄어쓰기·조사": [
        ("커플 스냅", [C], [], None, ""),
        ("커플의 가을", [C], [], None, "가을"),
        ("강아지와 함께", [PET], ["pet.dog"], None, "함께"),
        ("친구들이랑 바다", [F], [], None, "바다"),
        ("엄마랑 딸", [], [], None, "엄마랑 딸"),   # 사전만: 목적 없음. 가까움 비교를 켜면 가족(NEAREST_CASES)
        ("만삭사진", [E], ["event.maternity"], None, ""),
        ("졸업사진 찍기", [E], ["event.graduation"], None, ""),
    ],
}

# 사전에 없는 말 — 가까운 사전 예시로 보낸다(purpose_nearest, KURE-v1 이 받아져 있을 때만 검사).
# 잡혀야 하는 말과, 잡히면 안 되는 말(장소·옷·계절·무드 어휘)을 함께 고정한다.
NEAREST_CASES = {
    "사전에 없는 목적 말": [
        ("임부 사진", [E], ["event.maternity"], None, ""),
        ("학사모", [E], ["event.graduation"], None, ""),
        ("예식장", [W], ["wedding.ceremony"], None, ""),
        ("이력서 사진", [P], ["personal.id_photo"], None, ""),
        ("상품 촬영", [B], ["commercial.product"], None, ""),
        ("결혼기념일", [W], ["wedding.remind"], None, ""),
        ("커플링", [C], [], None, ""),
        ("부부 사진", [C], [], None, ""),
        ("가을 예식장", [W], ["wedding.ceremony"], None, "가을"),
        ("엄마랑 딸", [E], ["event.family"], None, "딸"),   # 엄마 ≈ 가족 — 엄마와 딸 사진은 가족 사진
        ("연회장 조명", [E], ["event.banquet"], None, "조명"),   # 연회장 사진은 연회다
        # 알려진 한계 — 강아지풀(식물)이 강아지로 간다. 글자로는 커플링(커플의 합성어)과 구분할 수 없다
        ("강아지풀", [PET], ["pet.dog"], None, ""),
    ],
    "사전에 없지만 목적이 아니다": [
        ("한강", [], [], None, "한강"),
        ("성수", [], [], None, "성수"),
        ("카페", [], [], None, "카페"),
        ("벚꽃", [], [], None, "벚꽃"),
        ("한옥", [], [], None, "한옥"),
        ("교복", [], [], None, "교복"),
        ("정장", [], [], None, "정장"),
        ("드레스", [], [], None, "드레스"),
        ("한복", [], [], None, "한복"),
        ("여행", [], [], None, "여행"),
        ("캠핑", [], [], None, "캠핑"),
        ("스튜디오", [], [], None, "스튜디오"),
        ("멍울멍울", [], [], None, "멍울멍울"),
        ("첫사랑", [], [], None, "첫사랑"),
        ("황혼", [], [], None, "황혼"),
        ("워크샵", [], [], None, "워크샵"),
    ],
}
